name: Run @crossdevice Devices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-24.04

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Install dependencies
      run: dotnet restore

    - name: Install Playwright Browsers
      run: pwsh bin/Debug/net8.0/playwright.ps1 install

    - name: Run @crossdevice Devices
      run: dotnet test --filter "Category=crossdevice"
