name: Run @crossdevice Devices

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Playwright and Dependencies
      run: npx playwright install --with-deps

    - name: Verify Playwright Installation
      run: ls -al /home/runner/.cache/ms-playwright

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release
